<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasTable('employee_data_updates')) {
            Schema::create('employee_data_updates', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id');
            $table->text('first_name');
            $table->text('last_name');
            $table->text('email');
            $table->text('email_personal');
            $table->text('date_of_birth');
            $table->text('date_of_birth_doc');
            $table->string('gender');
            $table->text('contact_no');
            $table->text('mother_tongue');
            $table->string('age');
            $table->text('place_of_birth');
            $table->string('blood_group');
            $table->string('marital_status');
            $table->text('pan_number');
            $table->text('aadhar_no');
            $table->string('category');
            $table->text('address');
            $table->text('address_com');
            $table->integer('added_by');
            $table->integer('updated_by');
            $table->text('updated_date');
            $table->text('facebook_link');
            $table->text('twitter_link');
            $table->text('blogger_link');
            $table->text('linkdedin_link');
            $table->text('google_plus_link');
            $table->text('instagram_link');
            $table->text('pinterest_link');
            $table->text('youtube_link');
            $table->text('father_name');
            $table->text('father_mobile');
            $table->text('father_gender');
            $table->text('father_occupation');
            $table->text('father_age');
            $table->text('father_qualification');
            $table->text('father_address');
            $table->text('mother_name');
            $table->text('mother_mobile');
            $table->text('mother_gender');
            $table->text('mother_occupation');
            $table->text('mother_age');
            $table->text('mother_qualification');
            $table->text('mother_address');
            $table->text('brother_name');
            $table->text('brother_mobile');
            $table->text('brother_gender');
            $table->text('brother_occupation');
            $table->text('brother_age');
            $table->text('brother_qualification');
            $table->text('brother_address');
            $table->text('sister_name');
            $table->text('sister_mobile');
            $table->text('sister_gender');
            $table->text('sister_occupation');
            $table->text('sister_age');
            $table->text('sister_qualification');
            $table->text('sister_address');
            $table->text('spouse_name');
            $table->text('spouse_mobile');
            $table->text('spouse_gender');
            $table->text('spouse_occupation');
            $table->text('spouse_age');
            $table->text('spouse_qualification');
            $table->text('spouse_address');
            $table->text('child1_name');
            $table->text('child1_mobile');
            $table->text('child1_gender');
            $table->text('child1_occupation');
            $table->text('child1_age');
            $table->text('child1_qualification');
            $table->text('child1_address');
            $table->text('child2_name');
            $table->text('child2_mobile');
            $table->text('child2_gender');
            $table->text('child2_occupation');
            $table->text('child2_age');
            $table->text('child2_qualification');
            $table->text('child2_address');
            $table->text('emergency_contact_relation')->nullable();
            $table->text('emergency_contact_name')->nullable();
            $table->text('emergency_contact_gender')->nullable();
            $table->text('emergency_contact_mobile')->nullable();
            $table->text('emergency_contact_age')->nullable();
            $table->text('emergency_contact_occupation')->nullable();
            $table->text('emergency_contact_qualification')->nullable();
            $table->text('emergency_contact_address')->nullable();
            $table->string('official_contact_no');
            $table->string('vehicle_type');
            $table->text('city_temp');
            $table->text('city');
            $table->text('state_temp');
            $table->text('state');
            $table->text('pin_temp');
            $table->text('pincode');
            $table->string('health_ins_opted');
            $table->string('pf_opted');
            $table->string('vehicle_no');
            $table->string('paytm_no');
            $table->text('skype_id');
            $table->integer('acceptance')->default(0);
            $table->text('acceptance_name');
            $table->text('acceptance_date');
            $table->integer('acceptance_basic')->default(0);
            $table->integer('acceptance_father')->default(0);
            $table->integer('acceptance_mother')->default(0);
            $table->integer('acceptance_emer')->default(0);
            $table->integer('acceptance_bro')->default(0);
            $table->integer('acceptance_sis')->default(0);
            $table->integer('acceptance_c1')->default(0);
            $table->integer('acceptance_c2')->default(0);
            $table->integer('acceptance_social')->default(0);
            $table->integer('acceptance_spouse')->default(0);
            $table->integer('emp_updated_dets')->default(0);
            $table->foreign('user_id')->references('user_id')->on('employees')->onDelete('cascade');
        });
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('employee_data_updates');
    }
};
